spring.datasource.url=jdbc:postgresql://localhost:5432/crypto_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# IMPORTANT
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===== OpenTelemetry / Micrometer Tracing =====

# Enable tracing
management.tracing.enabled=true

# Sample 100% of requests (for dev). In prod you usually lower this (0.1, 0.2, etc)
management.tracing.sampling.probability=1.0

# For now, use logging exporter so you can *see* traces in the console
logging.level.io.micrometer.tracing=DEBUG
logging.level.io.micrometer.tracing.exporter=DEBUG

# ==== Feature flags ====
# turn alerts ON/OFF
feature.alerts.enabled=true

# 30s between checks (you can change)
alerts.check-interval-ms=30000

# ====== Email alerts ======
alerts.email.to=your-email@example.com
alerts.email.from=crypto-tracker@example.com

# ====== SMTP config ======
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_SMTP_USERNAME
spring.mail.password=YOUR_SMTP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp

# Swagger UI always available
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Customize the URL
springdoc.swagger-ui.path=/swagger-ui
